version: "3"

services:
  nginx:     
    image: nginx:stable
    depends_on:
      - php
      - mysql     
    volumes:
      - ./build/nginx/www:/usr/share/nginx/html
      - ./build/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - net0

  php:
    build:
      context: ./build/php
    environment:
      - DB_SERVER_NAME=mysql
      - DB_USER_NAME=root
      - DB_PASSWORD=secret
      - DB_NAME=world
    expose:
      - 9000
    volumes:
      - ./build/nginx/www:/usr/share/nginx/html
    networks:
      - net0
 
  mysql:
    build:
      context: ./build/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - net0 
 
networks:
  net0: 
