version: '3.7'
services:
  web-static: 
    build:
      context: ./web-static
      args:
        WAR_FILE: spring-boot-sample-web-static-2.1.3.RELEASE.war
    networks:
      - backend

  web-ui:
    build: 
      context: ./web-ui
      args:
        JAR_FILE: spring-boot-sample-web-ui-2.1.3.RELEASE.jar
    networks:
      - backend
  
  haproxy:
    build: ./haproxy
    depends_on:
      - web-static
      - web-ui
    ports:
      - 9000:9000
    networks:
      - backend
      - frontend 

networks:
  frontend:
    driver: bridge
  
  backend:
    driver: bridge
